### ISSUE TITLE
git: "unknown"

### ISSUE THREAD

**Issue by mattiaerre** [bahmutov/version-middleware#3]
# Description

The `/version` endpoint returns a JSON w/ the `git` property set to `unknown`

Although I am running my app on Heroku, I get this payload when I request the `/version` endpoint:

```json
{"version":"1.9.0","git":"unknown"}
```

Looking at the code I've found that this middleware is internally using the `last-commit` library and as per the [README.md](https://github.com/bahmutov/last-commit#heroku) it looks like Heroku should be covered.

this is the express app I am referring to:

[https://pink-pineapple.herokuapp.com/version](https://pink-pineapple.herokuapp.com/version)

thanks,

**Comment by mattiaerre** [comment]
// cc @bahmutov

**Comment by bahmutov** [comment]
But does Heroku actually have git information? I thought you pushed code there, but just the code, not the `.git` folder. For example, this is why I had to put the build commit into special file, check it in, etc, all on CI server: https://glebbahmutov.com/blog/deployed-commit/

**Comment by mattiaerre** [comment]
Hi @bahmutov yes I do but as per your comment here https://github.com/bahmutov/last-commit#heroku I was under the impression that Heroku was able to automagically pick it up for me 😊  I will try to see how can I integrate w/ what you are suggesting

**Comment by bahmutov** [comment]
Yeah, the Heroku `SOURCE_VERSION` is only available during compile phase, not in deployed box, according to https://devcenter.heroku.com/articles/buildpack-api#bin-compile-summary

**Comment by mattiaerre** [comment]
splendid, so I need to set that variable at some point; thanks for that. I am going to close this issue then.
